
{{- if .Values.dockerRegistryCredentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerRegistryCredentials }}
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
{{- end }}