{{ range $path, $_ :=  .Files.Glob  "tmp/secrets/files/*" }}
---
apiVersion: v1
kind: Secret
type: Opaque
{{ $file := trimPrefix "tmp/secrets/files/" $path -}}
{{ $ext := $file | ext -}}
{{ $name := trimSuffix $ext $file -}}
metadata: 
  name: {{ print $name }}
data: 
  {{ print $file }}: {{ $.Files.Get $path | b64enc }}
{{ end }}