{{- if .Values.configs.secrets.secret }}
{{- range $i, $value := .Values.configs.secrets.secret }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}
type: Opaque
data: 
  {{- range $key, $val := $value.data }}
  {{ print $key }}: {{ print $val | b64enc }}  
  {{ end -}}
{{ end -}}
{{- end }}
---
{{- if .Values.configs.secrets.externalSecrets }}
{{- range $i, $value := .Values.secretsFileExternal }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}
type: Opaque
data: 
  {{- with $value.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{ end -}}
{{- end }}

---
{{- if .Values.configs.secrets.externalSecrets }}
{{- range $i, $value := .Values.secretsKeyValueExternal }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}
type: Opaque
data: 
  {{- range $key, $val := $value.data }}
  {{ print $key }}: {{ print $val | b64enc -}}  
  {{ end -}}
{{ end -}}
{{- end }}

---
{{- if .Values.dockerRegistryCredentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerRegistryCredentials }}
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
{{- end }}
---
{{- if .Values.configs.secrets.externalSecrets }}
{{- range $i, $value := .Values.secretsTLSExternal }}
---
apiVersion: v1
data:
  {{- with $value.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $value.name }}
type: kubernetes.io/tls
{{ end -}}
{{- end }}